ConsenSys.QBS.Web/Models/ErrorViewModel.cs
namespace ConsenSys.QBS.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ConsenSys.QBS.Web/Models/QbsApiResponseModel.cs
namespace ConsenSys.QBS.Web.Models;

public class QbsApiResponseModel
{
    public ConsortiumCollection Consortiums { get; set; }

    public ConsortiumMemberCollection ConsortiumMembers { get; set; }

    public Invite Invite { get; set; }
}

ConsenSys.QBS.Web/Controllers/ConsortiumManagementController.cs
using ConsenSys.QBS.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http.Headers;

namespace ConsenSys.QBS.Web.Controllers;

public class ConsortiumManagementController : Controller
{
    private static readonly HttpClient httpClient = new ();
    private readonly QbsClient qbs = new (httpClient);

    private readonly Guid subscriptionId;
    private readonly string appName;
    private readonly string resourceGroup;
    private readonly string managedResourceGroup;
    private readonly string bearerToken;
    private readonly string location;

    public ConsortiumManagementController(IConfiguration configuration)
    {
        subscriptionId = Guid.Parse(configuration["QBS:SubscriptionId"]);
        appName = configuration["QBS:AppName"];
        resourceGroup = configuration["QBS:ResourceGroup"];
        managedResourceGroup = configuration["QBS:ManagedResourceGroup"];
        location = configuration["QBS:Location"];
        bearerToken = configuration["QBS:BearerToken"];

        httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", bearerToken);
    }

    public async Task<IActionResult> Index()
    {
        var consortiums = await qbs.ListConsortiumsAsync(subscriptionId, location);
        var members = await qbs.ListMembersAsync(subscriptionId, resourceGroup, appName, includeDeleted: false, includeRemoved: false);

        var model = new QbsApiResponseModel
        {
            Consortiums = consortiums,
            ConsortiumMembers = members
        };

        return View(model);
    }

    public async Task<IActionResult> Invite()
    {
        var inviteRequest = new InviteCreateRequestBody
        {
            InviterEmail = "stefano.tempesta@consensys.net",
            InviteeSubscriptionId = Guid.Parse("fcb0cf94-e971-4830-8f75-17b1edc6f5b1"),
            ExpireInDays = 10,
            InviteeEmail = "stefano.tempesta@outlook.com",
            InviteeRole = "MEMBER"
        };
        var invite = await qbs.CreateInviteAsync(subscriptionId, resourceGroup, appName, inviteRequest);

        var model = new QbsApiResponseModel
        {
            Invite = invite
        };

        return View(model);
    }

    public async Task<IActionResult> Remove(string memberName)
    {
        await qbs.RemoveMemberAsync(subscriptionId, resourceGroup, appName, memberNameToRemove: memberName);

        return View();
    }
}

ConsenSys.QBS.Web/Controllers/HomeController.cs
using ConsenSys.QBS.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ConsenSys.QBS.Web.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error() => View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
}

ConsenSys.QBS.Web/Views/ConsortiumManagement/Index.cshtml
@model QbsApiResponseModel

<h1 class="display-6">Consortiums</h1>
<ul>
@foreach (var c in Model.Consortiums.Value)
{
    <li>@c.Name, protocol: @c.Protocol</li>
}
</ul>

<h1 class="display-6">Consortium Members</h1>
<ul>
@foreach (var c in Model.ConsortiumMembers.Value)
{
    <li>@c.Name, region: @c.Region, created on: @c.CreatedDate</li>
}
</ul>

<hr class="m-5" />

<a asp-action="Invite" class="btn btn-outline-primary">Invite Member</a>

ConsenSys.QBS.Web/Views/ConsortiumManagement/Invite.cshtml
@model QbsApiResponseModel

<h1 class="display-6">Invite Code: <code>@Model.Invite.InviteCode</code></h1>

ConsenSys.QBS.Web/Views/Home/Index.cshtml
<div class="m-5">
    <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
            <a asp-controller="ConsortiumManagement" asp-action="Index">Consortium Management</a>
        </li>
        <li class="nav-item">
            <a asp-controller="Invites" asp-action="Index">Invites</a>
        </li>
        <li class="nav-item">
            <a asp-controller="Locations" asp-action="Index">Locations</a>
        </li>
    </ul>
</div>

ConsenSys.QBS.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ConsenSys QBS API Client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ConsenSys.QBS.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">ConsenSys.QBS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="ConsortiumManagement" asp-action="Index">Consortium Management</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Invites" asp-action="Index">Invites</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Locations" asp-action="Index">Locations</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>